# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeNotifier < Formula
  desc "Notification dispatcher for Claude Code hooks"
  homepage "https://github.com/felipeelias/claude-notifier"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipeelias/claude-notifier/releases/download/v0.1.0/claude-notifier_0.1.0_darwin_amd64.tar.gz"
      sha256 "8c146d18bc92596cd5af9038e51ad0378a09dac4a11bd75833bfa80fff548324"

      define_method(:install) do
        bin.install "claude-notifier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipeelias/claude-notifier/releases/download/v0.1.0/claude-notifier_0.1.0_darwin_arm64.tar.gz"
      sha256 "f8182413cb7452fa309a238484db45b779be7263eb80e3f0648ef8f534946884"

      define_method(:install) do
        bin.install "claude-notifier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-notifier/releases/download/v0.1.0/claude-notifier_0.1.0_linux_amd64.tar.gz"
      sha256 "39a6aca7fd3106806c2d461b90ac02856d79851ff9b71c9f27c639fbb99e5797"
      define_method(:install) do
        bin.install "claude-notifier"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-notifier/releases/download/v0.1.0/claude-notifier_0.1.0_linux_arm64.tar.gz"
      sha256 "60a0da8c633e444af77dbc985b0f29d0fc9cf48729ead96c5c1d1f35c1a4c927"
      define_method(:install) do
        bin.install "claude-notifier"
      end
    end
  end
end
