# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/felipeelias/claude-statusline"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.9.0/claude-statusline_0.9.0_darwin_amd64.tar.gz"
      sha256 "db70f395533570c36ab16fbca6b93d558d5a521b5f2fa9f03d04f54e70d95c7d"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.9.0/claude-statusline_0.9.0_darwin_arm64.tar.gz"
      sha256 "7056c5891bb30e005329a6b08d5b73aeb9596417b69a2eb07c38ffa8ca862972"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.9.0/claude-statusline_0.9.0_linux_amd64.tar.gz"
      sha256 "d8310cb9dbd60f87daa9407a9017fab973d8651dffb4eb7b9c2a695a69b118dd"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.9.0/claude-statusline_0.9.0_linux_arm64.tar.gz"
      sha256 "7df87185e42340a6f7f4cf776718890bb5d8ec5ccaaccb62121e734507570175"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
