# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/felipeelias/claude-statusline"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.1.1/claude-statusline_0.1.1_darwin_amd64.tar.gz"
      sha256 "b21e7b782133ae251883c8cefdcf8567e11aad2bc878c418ea88b59cb630f438"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.1.1/claude-statusline_0.1.1_darwin_arm64.tar.gz"
      sha256 "343b45dec8293aed558d8035ecbae9af224501c3c40dc2e82f6caeeaee3fb5c0"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.1.1/claude-statusline_0.1.1_linux_amd64.tar.gz"
      sha256 "563f56cbb4bdcfeda48113707d8f80d07b4748fdaca3f36109f252a3649d885f"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.1.1/claude-statusline_0.1.1_linux_arm64.tar.gz"
      sha256 "1e20252c063f3e74d939bb0118940077dcbe8fffe2ddfafecb55cb6d92979c98"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
