# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/felipeelias/claude-statusline"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.3.0/claude-statusline_0.3.0_darwin_amd64.tar.gz"
      sha256 "edd4374c7527c4a56df68f20ee721d2f4c8a35fa579835622d554ac132b1e1f9"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.3.0/claude-statusline_0.3.0_darwin_arm64.tar.gz"
      sha256 "e538ce6cf743a7c7ce51f9ca82a6725fc9a3a740d99d81c3842fb06253ce07f3"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.3.0/claude-statusline_0.3.0_linux_amd64.tar.gz"
      sha256 "4d32315686941c6eb1ea9acac381c7561aa0891cd64536543ebc0c48ccc652ee"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipeelias/claude-statusline/releases/download/v0.3.0/claude-statusline_0.3.0_linux_arm64.tar.gz"
      sha256 "9c69c6a09618841ca1534c3188a00407cbb7a21002b11b82adcbe15fd5443e73"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
